nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-docs.cjs
    spec: "https://deno.land/x/yarn_plugin_docs@2.0/bundles/@yarnpkg/plugin-docs.js"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
